name: base_environment
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - pip==22.3.1
  - python=3.9
  - pytorch
  - pip:
    - azureml-defaults==1.38.0
    - pyraisdk==0.1.0
    - GPUtil
    - psutil
    