
$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: xiaoyan-deployment-gputest10
endpoint_name: xiaoyan-endpoint-gputest10
model:
  path: ./storage/model/
code_configuration:
  code: ./storage/code/
  scoring_script: score.py
environment: 
  conda_file: ./storage/environment/conda.yml
  image: xiaoyanacr.azurecr.io/test/gpu-test:1209-1
instance_type: Standard_NC6s_v3
instance_count: 1
