$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: xiaoyan-deployment-gputest2
endpoint_name: xiaoyan-endpoint-gputest2
environment:
  image: xiaoyanacr.azurecr.io/test/aml-pygputest:1209-1
  inference_config:
    liveness_route:
      port: 8000
      path: /liveness
    readiness_route:
      port: 8000
      path: /readiness
    scoring_route:
      port: 8000
      path: /execute
instance_type: Standard_NC6s_v3
instance_count: 1
