$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: pytest-deployment4
endpoint_name: pytest-endpoint4
environment:
  image: xiaoyanacr.azurecr.io/test/aml-pytest:1107-4
  inference_config:
    liveness_route:
      port: 8000
      path: /liveness
    readiness_route:
      port: 8000
      path: /readiness
    scoring_route:
      port: 8000
      path: /hostname
instance_type: Standard_DS2_v2
instance_count: 1
