$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: pytest-deployment1
endpoint_name: pytest-endpoint1
environment:
  image: xiaoyanacr.azurecr.io/test/aml-pytest:1208-1
  inference_config:
    liveness_route:
      port: 8000
      path: /liveness
    readiness_route:
      port: 8000
      path: /readiness
    scoring_route:
      port: 8000
      path: /score
instance_type: Standard_DS2_v2
instance_count: 1
